### ISSUE TITLE
Stretch to full width

### ISSUE THREAD

**Issue by papamauro** [richardtallent/vue-scrolling-table-sample#1]
Hello,
this is a really cool component. Is there a way to stretch the table to fill 100% of container width if it is not large enough?
I tried the bulma table helper **[is-fullwidth](https://bulma.io/documentation/elements/table/)**, which should do exactly what I'm trying to achieve, but it doesn't work...

Thank you in advance

**Comment by richardtallent** [comment]
Thanks!

This component isn't responsible for rendering the headers or body, so it doesn't really have a role in  managing your column widths.

One mechanism I could imagine is putting a resize observer on the container, and each time it changes, re-compute the "unused" width (by subtracting the header row width from the container), and if there is any, add that to the default width of the column that has been deemed to be the "flex" column. Runtime changes to specified column widths would also need to trigger this.

Here's a very rough idea, less the observer logic. When rendering the TH/TD elements, you'd use the `usedColumnWidths` array instead of the default column definition widths. Untested code:

```
data: {
    columns: [...],
    containerWidth: 500, // this needs to be updated live by the container observer
}.
computed: {
    useColumnWidths() {
        const totalDefaultRowWidth = this.columns.reduce((t, c) => t += c.width)
        const extraWidth = Math.Max(0, this.containerWidth - totalDefaultRowWidth)
        return this.columns.map(c => c.isFlexColumn ? `calc(${c.width} + ${extraWidth}px)` : c.width)
    },
}
```

This assumes you specify your default column widths in integer pixels. I rarely use pixels for anything other than borders (I'm an em/rem fan). Since JavaScript doesn't have a native way to do the equivalent of CSS's `calc()` to manage units of measure, you'd need to another way to calculate the total default row width so you know how much to stretch the flex column.

One solution is to create an element somewhere on the page (doesn't have to be in the table) that has a dynamic `:style="width:calc(...insert column default widths here with + between them...)`. Then you can put a `ref` on that element and observe its width inside `useColumnWidths` rather than using the `totalWidth` sum.

So, overall, I think what you're asking for can be done, but it would be the responsibility of whatever table component you're building *with* this component, since that's where you would have access to the default column widths, etc.
